RenrenYGO/Team-06-BSCS3CD

application/config/autoload.php, application/config/routes.php, application/controllers/Login.php, application/controllers/Logout.php, application/controllers/Pages.php, application/controllers/Posts.php, application/libraries/Sitelayout.php, application/models/Login_model.php, application/models/Post_model.php, application/views/posts/create.php, application/views/registration/login.php, application/views/templates/content.php, application/views/templates/footer.php, application/views/templates/header.php
Updated login, logout and posts
=> variousfixes to master

application/controllers/Posts.php
fixed the post visibility issue
=> fixed posts

application/views/registration/check.js, application/views/registration/register.php, application/views/registration/style.css
=> revised register page

schema/registration.sql
=> Updated Schema File again

application/controllers/Posts.php, application/models/Post_model.php, application/views/posts/view.php
=> Fixed fatal bugs

application/views/posts/prof.css, application/views/posts/profile.html
=> Profile page

application/controllers/Posts.php, application/controllers/Replies.php, application/models/Post_model.php, application/models/Replies_model.php, application/views/posts/index.php, application/views/posts/view.php, schema/registration.sql
=> Added temporary reply count

application/controllers/Pages.php, application/views/templates/navbar3.php, application/views/templates/prof.css, application/views/templates/profile.php
=> profile linked

application/config/autoload.php, application/controllers/Newsletter.php, application/models/Newsletter_model.php, application/views/posts/view.php, application/views/registration/newsletter.php, application/views/templates/footer.php
added a prototype newsletter function
=> beta newsletter function

application/views/registration/forgot.php
=> Forgot layout

schema/registration.sql
=> registration

application/views/posts/index.php, application/views/templates/footer.php
+ fixed directory path of help center and faqs
=> search layout, reply count layout

application/controllers/Pages.php, application/controllers/Replies.php, application/controllers/Users.php, application/models/Replies_model.php, application/models/User_model.php, application/views/posts/view.php, application/views/templates/profile.php, application/views/users/index.php, schema/registration.sql
Various fixes and mainly improvements
=> Various fixes and mainly improvements

application/controllers/Posts.php, application/controllers/Threads.php, application/views/posts/index.php, application/views/posts/style.css, application/views/templates/navbar2.php, application/views/templates/navbar3.php
=> added tags in post page and anchor for popular tags

application/config/autoload.php, application/controllers/Helpcenter.php, application/models/Helpcenter_model.php, application/views/templates/help.php, schema/registration.sql
=> Added helpcenter functionality, updated schema

application/controllers/Helpcenter.php, application/controllers/Registration.php, application/controllers/Users.php, application/models/Login_model.php, application/models/User_model.php, application/views/posts/edit.php, application/views/users/index.php
Added change password, fixed helpcenter error
=> Added change password, fixed helpcenter error

application/config/routes.php, application/controllers/Pages.php, application/controllers/Users.php, application/models/Post_model.php, application/models/User_model.php, application/views/profiles/index.php, application/views/registration/forgot.php, application/views/templates/navbar2.php, application/views/templates/navbar3.php, application/views/templates/profile.php
Profile posts and fixed forgot password
=> Profile posts and fixed forgot password

application/controllers/Posts.php, application/models/Post_model.php, application/views/posts/index.php, application/views/templates/profile.php, schema/registration.sql
Added post count, link button to users via name
=> Added post count, link button to users via name

application/config/autoload.php, application/controllers/Changepass.php, application/controllers/Pages.php, application/models/Changepass_model.php, application/models/Post_model.php, application/models/User_model.php, application/views/templates/changepassword.php
Separated change password from edit user.
=> Separated change password from edit user.

application/views/templates/navbar2.php, application/views/templates/navbar3.php
added Account Settings in dropdown
=> added change password in dropdown

Team-06-BSCS3CD.side, application/controllers/Newsletter.php, application/views/templates/footer.php, schema/registration.sql
newsletter in footer now has functionality, added selenium test file
=> newsletter in footer now has functionality, added selenium test file

application/controllers/Login.php, application/controllers/Registration.php, application/models/Changepass_model.php, application/models/Login_model.php, application/models/User_model.php, schema/registration.sql
=> Strengthened Password Hashing

application/controllers/Changepass.php, application/controllers/Pages.php, application/controllers/Popularity.php, application/controllers/Posts.php, application/controllers/Registration.php, application/controllers/Replies.php, application/controllers/Users.php, application/models/Post_model.php, application/views/posts/index.php, application/views/posts/view.php
Fixed reactions, controller exploits, and post popularity
=> Fixed reactions, controller exploits, and post popularity

application/controllers/Forgot.php, application/models/Forgot_model.php, application/views/registration/forgot.php, application/views/registration/register.php
=> Minor changes to forgot

application/views/posts/view.php, application/views/templates/about.php, application/views/templates/footer.php, application/views/templates/help.php, application/views/templates/navbar2.php, application/views/templates/navbar3.php, application/views/templates/profile.php
=> Fixed some div mismatches
